#ifndef ERRORCODES_HPP
#define ERRORCODES_HPP

#include <cstdint>

#define EC_FAILED(ec) ((ec) != ErrorCode::OK)
#define EC_CHECK(ecVar, expr) (ecVar) = (expr); if (EC_FAILED(ecVar)) return (ecVar);

enum class ErrorCode : uint32_t
{
	OK = 0,

	// EXECUTION
	COMMAND_FAILED_EXECUTION			= 2500,

	// FILESYSTEM
	FILE_NOT_FOUND						= 5000,
	FILE_READ_ERROR						= 5001,

	// GRAPHICS
	// Shaders
	SHADER_COMPILE_FAILED				= 10000,
	SHADER_COULD_NOT_READ_FILE			= 10001,
	SHADER_COULD_NOT_READ_BYTECODE		= 10002,
	SHADER_REGISTER_INVALID_TYPE		= 10003,
	SHADER_NAME_ALREADY_EXISTS			= 10004,
	SHADER_INVALID_BYTECODE_ALIGNMENT	= 10005,
	SHADER_REFLECTION_ERROR				= 10006,

	// Materials
	MATERIAL_NAME_ALREADY_EXISTS		= 20004,
	MATERIAL_COULD_NOT_FETCH_SHADERS	= 20005,

	// MEMORY
	MEMORY_IS_NULL						= 20000
};

#endif