#ifndef ERRORCODES_HPP
#define ERRORCODES_HPP

#include <cstdint>

#define EC_FAILED(ec) ((ec) != ErrorCode::OK)
#define EC_RETURN_FAILED(ec) if ( (ec) != ErrorCode::OK) return (ec);
#define EC_RETURN_FAILED_INT(ec) if ( (ec) != ErrorCode::OK) return static_cast<int>(ec);
#define EC_CHECK(ecVar, expr) (ecVar) = (expr); if (EC_FAILED(ecVar)) return (ecVar);
#define EC_INT(ec) static_cast<int>(ec)

enum class ErrorCode : uint32_t
{
	OK = 0,

	// EXECUTION
	COMMAND_FAILED_EXECUTION			= 2500,

	// FILESYSTEM
	FILE_NOT_FOUND						= 5000,
	FILE_READ_ERROR						= 5001,

	// GRAPHICS
	// Shaders
	SHADER_COMPILE_FAILED				= 10000,
	SHADER_COULD_NOT_READ_FILE			= 10001,
	SHADER_COULD_NOT_READ_BYTECODE		= 10002,
	SHADER_REGISTER_INVALID_TYPE		= 10003,
	SHADER_NAME_ALREADY_EXISTS			= 10004,
	SHADER_INVALID_BYTECODE_ALIGNMENT	= 10005,
	SHADER_REFLECTION_ERROR				= 10006,

	// Materials
	MATERIAL_NAME_ALREADY_EXISTS		= 20004,
	MATERIAL_COULD_NOT_FETCH_SHADERS	= 20005,

	// MEMORY
	MEMORY_IS_NULL						= 20000,

	// REFLECTION
	REFLECTION_POINTER_IS_NULL			= 30000,

	// SCENES
	SCENE_UNTRACKED_SCENE_REFERENCE		= 40000,
	SCENE_ALREADY_ACTIVE				= 40001,

	// ASSETS
	ASSETS_IMPORT_ERROR					= 50000,
	ASSETS_MODEL_INCOMPLETE				= 50001,
	ASSETS_MODEL_NO_ROOT				= 50002
};

#endif